/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiUcetniRouteImport } from './routes/ai-ucetni'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DphRouteImport } from './routes/dph'
import { Route as KontrolniHlaseniRouteImport } from './routes/kontrolni-hlaseni'
import { Route as NastaveniRouteImport } from './routes/nastaveni'
import { Route as NavodRouteImport } from './routes/navod'
import { Route as OsnovaRouteImport } from './routes/osnova'
import { Route as PrehledRouteImport } from './routes/prehled'
import { Route as PrijateRouteImport } from './routes/prijate'
import { Route as PriznaniRouteImport } from './routes/priznani'
import { Route as UctyRouteImport } from './routes/ucty'
import { Route as ApiAiZauctovaniRouteImport } from './routes/api/ai-zauctovani'
import { Route as FakturyIndexRouteImport } from './routes/faktury.index'
import { Route as FakturyNovaRouteImport } from './routes/faktury.nova'
import { Route as FakturyIdIndexRouteImport } from './routes/faktury.$id.index'
import { Route as FakturyIdUpravitRouteImport } from './routes/faktury.$id.upravit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiUcetniRoute = AiUcetniRouteImport.update({
  id: '/ai-ucetni',
  path: '/ai-ucetni',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DphRoute = DphRouteImport.update({
  id: '/dph',
  path: '/dph',
  getParentRoute: () => rootRouteImport,
} as any)
const KontrolniHlaseniRoute = KontrolniHlaseniRouteImport.update({
  id: '/kontrolni-hlaseni',
  path: '/kontrolni-hlaseni',
  getParentRoute: () => rootRouteImport,
} as any)
const NastaveniRoute = NastaveniRouteImport.update({
  id: '/nastaveni',
  path: '/nastaveni',
  getParentRoute: () => rootRouteImport,
} as any)
const NavodRoute = NavodRouteImport.update({
  id: '/navod',
  path: '/navod',
  getParentRoute: () => rootRouteImport,
} as any)
const OsnovaRoute = OsnovaRouteImport.update({
  id: '/osnova',
  path: '/osnova',
  getParentRoute: () => rootRouteImport,
} as any)
const PrehledRoute = PrehledRouteImport.update({
  id: '/prehled',
  path: '/prehled',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijateRoute = PrijateRouteImport.update({
  id: '/prijate',
  path: '/prijate',
  getParentRoute: () => rootRouteImport,
} as any)
const PriznaniRoute = PriznaniRouteImport.update({
  id: '/priznani',
  path: '/priznani',
  getParentRoute: () => rootRouteImport,
} as any)
const UctyRoute = UctyRouteImport.update({
  id: '/ucty',
  path: '/ucty',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiZauctovaniRoute = ApiAiZauctovaniRouteImport.update({
  id: '/api/ai-zauctovani',
  path: '/api/ai-zauctovani',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturyIndexRoute = FakturyIndexRouteImport.update({
  id: '/faktury/',
  path: '/faktury/',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturyNovaRoute = FakturyNovaRouteImport.update({
  id: '/faktury/nova',
  path: '/faktury/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturyIdIndexRoute = FakturyIdIndexRouteImport.update({
  id: '/faktury/$id/',
  path: '/faktury/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturyIdUpravitRoute = FakturyIdUpravitRouteImport.update({
  id: '/faktury/$id/upravit',
  path: '/faktury/$id/upravit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-ucetni': typeof AiUcetniRoute
  '/auth': typeof AuthRoute
  '/dph': typeof DphRoute
  '/kontrolni-hlaseni': typeof KontrolniHlaseniRoute
  '/nastaveni': typeof NastaveniRoute
  '/navod': typeof NavodRoute
  '/osnova': typeof OsnovaRoute
  '/prehled': typeof PrehledRoute
  '/prijate': typeof PrijateRoute
  '/priznani': typeof PriznaniRoute
  '/ucty': typeof UctyRoute
  '/api/ai-zauctovani': typeof ApiAiZauctovaniRoute
  '/faktury/nova': typeof FakturyNovaRoute
  '/faktury/': typeof FakturyIndexRoute
  '/faktury/$id/upravit': typeof FakturyIdUpravitRoute
  '/faktury/$id/': typeof FakturyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-ucetni': typeof AiUcetniRoute
  '/auth': typeof AuthRoute
  '/dph': typeof DphRoute
  '/kontrolni-hlaseni': typeof KontrolniHlaseniRoute
  '/nastaveni': typeof NastaveniRoute
  '/navod': typeof NavodRoute
  '/osnova': typeof OsnovaRoute
  '/prehled': typeof PrehledRoute
  '/prijate': typeof PrijateRoute
  '/priznani': typeof PriznaniRoute
  '/ucty': typeof UctyRoute
  '/api/ai-zauctovani': typeof ApiAiZauctovaniRoute
  '/faktury/nova': typeof FakturyNovaRoute
  '/faktury': typeof FakturyIndexRoute
  '/faktury/$id/upravit': typeof FakturyIdUpravitRoute
  '/faktury/$id': typeof FakturyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-ucetni': typeof AiUcetniRoute
  '/auth': typeof AuthRoute
  '/dph': typeof DphRoute
  '/kontrolni-hlaseni': typeof KontrolniHlaseniRoute
  '/nastaveni': typeof NastaveniRoute
  '/navod': typeof NavodRoute
  '/osnova': typeof OsnovaRoute
  '/prehled': typeof PrehledRoute
  '/prijate': typeof PrijateRoute
  '/priznani': typeof PriznaniRoute
  '/ucty': typeof UctyRoute
  '/api/ai-zauctovani': typeof ApiAiZauctovaniRoute
  '/faktury/nova': typeof FakturyNovaRoute
  '/faktury/': typeof FakturyIndexRoute
  '/faktury/$id/upravit': typeof FakturyIdUpravitRoute
  '/faktury/$id/': typeof FakturyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-ucetni'
    | '/auth'
    | '/dph'
    | '/kontrolni-hlaseni'
    | '/nastaveni'
    | '/navod'
    | '/osnova'
    | '/prehled'
    | '/prijate'
    | '/priznani'
    | '/ucty'
    | '/api/ai-zauctovani'
    | '/faktury/nova'
    | '/faktury/'
    | '/faktury/$id/upravit'
    | '/faktury/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-ucetni'
    | '/auth'
    | '/dph'
    | '/kontrolni-hlaseni'
    | '/nastaveni'
    | '/navod'
    | '/osnova'
    | '/prehled'
    | '/prijate'
    | '/priznani'
    | '/ucty'
    | '/api/ai-zauctovani'
    | '/faktury/nova'
    | '/faktury'
    | '/faktury/$id/upravit'
    | '/faktury/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-ucetni'
    | '/auth'
    | '/dph'
    | '/kontrolni-hlaseni'
    | '/nastaveni'
    | '/navod'
    | '/osnova'
    | '/prehled'
    | '/prijate'
    | '/priznani'
    | '/ucty'
    | '/api/ai-zauctovani'
    | '/faktury/nova'
    | '/faktury/'
    | '/faktury/$id/upravit'
    | '/faktury/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiUcetniRoute: typeof AiUcetniRoute
  AuthRoute: typeof AuthRoute
  DphRoute: typeof DphRoute
  KontrolniHlaseniRoute: typeof KontrolniHlaseniRoute
  NastaveniRoute: typeof NastaveniRoute
  NavodRoute: typeof NavodRoute
  OsnovaRoute: typeof OsnovaRoute
  PrehledRoute: typeof PrehledRoute
  PrijateRoute: typeof PrijateRoute
  PriznaniRoute: typeof PriznaniRoute
  UctyRoute: typeof UctyRoute
  ApiAiZauctovaniRoute: typeof ApiAiZauctovaniRoute
  FakturyNovaRoute: typeof FakturyNovaRoute
  FakturyIndexRoute: typeof FakturyIndexRoute
  FakturyIdUpravitRoute: typeof FakturyIdUpravitRoute
  FakturyIdIndexRoute: typeof FakturyIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ucetni': {
      id: '/ai-ucetni'
      path: '/ai-ucetni'
      fullPath: '/ai-ucetni'
      preLoaderRoute: typeof AiUcetniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dph': {
      id: '/dph'
      path: '/dph'
      fullPath: '/dph'
      preLoaderRoute: typeof DphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontrolni-hlaseni': {
      id: '/kontrolni-hlaseni'
      path: '/kontrolni-hlaseni'
      fullPath: '/kontrolni-hlaseni'
      preLoaderRoute: typeof KontrolniHlaseniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nastaveni': {
      id: '/nastaveni'
      path: '/nastaveni'
      fullPath: '/nastaveni'
      preLoaderRoute: typeof NastaveniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navod': {
      id: '/navod'
      path: '/navod'
      fullPath: '/navod'
      preLoaderRoute: typeof NavodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osnova': {
      id: '/osnova'
      path: '/osnova'
      fullPath: '/osnova'
      preLoaderRoute: typeof OsnovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prehled': {
      id: '/prehled'
      path: '/prehled'
      fullPath: '/prehled'
      preLoaderRoute: typeof PrehledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijate': {
      id: '/prijate'
      path: '/prijate'
      fullPath: '/prijate'
      preLoaderRoute: typeof PrijateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priznani': {
      id: '/priznani'
      path: '/priznani'
      fullPath: '/priznani'
      preLoaderRoute: typeof PriznaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ucty': {
      id: '/ucty'
      path: '/ucty'
      fullPath: '/ucty'
      preLoaderRoute: typeof UctyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-zauctovani': {
      id: '/api/ai-zauctovani'
      path: '/api/ai-zauctovani'
      fullPath: '/api/ai-zauctovani'
      preLoaderRoute: typeof ApiAiZauctovaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faktury/': {
      id: '/faktury/'
      path: '/faktury'
      fullPath: '/faktury/'
      preLoaderRoute: typeof FakturyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faktury/nova': {
      id: '/faktury/nova'
      path: '/faktury/nova'
      fullPath: '/faktury/nova'
      preLoaderRoute: typeof FakturyNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faktury/$id/': {
      id: '/faktury/$id/'
      path: '/faktury/$id'
      fullPath: '/faktury/$id/'
      preLoaderRoute: typeof FakturyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faktury/$id/upravit': {
      id: '/faktury/$id/upravit'
      path: '/faktury/$id/upravit'
      fullPath: '/faktury/$id/upravit'
      preLoaderRoute: typeof FakturyIdUpravitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiUcetniRoute: AiUcetniRoute,
  AuthRoute: AuthRoute,
  DphRoute: DphRoute,
  KontrolniHlaseniRoute: KontrolniHlaseniRoute,
  NastaveniRoute: NastaveniRoute,
  NavodRoute: NavodRoute,
  OsnovaRoute: OsnovaRoute,
  PrehledRoute: PrehledRoute,
  PrijateRoute: PrijateRoute,
  PriznaniRoute: PriznaniRoute,
  UctyRoute: UctyRoute,
  ApiAiZauctovaniRoute: ApiAiZauctovaniRoute,
  FakturyNovaRoute: FakturyNovaRoute,
  FakturyIndexRoute: FakturyIndexRoute,
  FakturyIdUpravitRoute: FakturyIdUpravitRoute,
  FakturyIdIndexRoute: FakturyIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
