/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NastaveniRouteImport } from './routes/nastaveni'
import { Route as NavodRouteImport } from './routes/navod'
import { Route as PrehledRouteImport } from './routes/prehled'
import { Route as FakturyIndexRouteImport } from './routes/faktury.index'
import { Route as FakturyNovaRouteImport } from './routes/faktury.nova'
import { Route as FakturyIdIndexRouteImport } from './routes/faktury.$id.index'
import { Route as FakturyIdUpravitRouteImport } from './routes/faktury.$id.upravit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NastaveniRoute = NastaveniRouteImport.update({
  id: '/nastaveni',
  path: '/nastaveni',
  getParentRoute: () => rootRouteImport,
} as any)
const NavodRoute = NavodRouteImport.update({
  id: '/navod',
  path: '/navod',
  getParentRoute: () => rootRouteImport,
} as any)
const PrehledRoute = PrehledRouteImport.update({
  id: '/prehled',
  path: '/prehled',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturyIndexRoute = FakturyIndexRouteImport.update({
  id: '/faktury/',
  path: '/faktury/',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturyNovaRoute = FakturyNovaRouteImport.update({
  id: '/faktury/nova',
  path: '/faktury/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturyIdIndexRoute = FakturyIdIndexRouteImport.update({
  id: '/faktury/$id/',
  path: '/faktury/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturyIdUpravitRoute = FakturyIdUpravitRouteImport.update({
  id: '/faktury/$id/upravit',
  path: '/faktury/$id/upravit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nastaveni': typeof NastaveniRoute
  '/navod': typeof NavodRoute
  '/prehled': typeof PrehledRoute
  '/faktury/nova': typeof FakturyNovaRoute
  '/faktury/': typeof FakturyIndexRoute
  '/faktury/$id/upravit': typeof FakturyIdUpravitRoute
  '/faktury/$id/': typeof FakturyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nastaveni': typeof NastaveniRoute
  '/navod': typeof NavodRoute
  '/prehled': typeof PrehledRoute
  '/faktury/nova': typeof FakturyNovaRoute
  '/faktury': typeof FakturyIndexRoute
  '/faktury/$id/upravit': typeof FakturyIdUpravitRoute
  '/faktury/$id': typeof FakturyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nastaveni': typeof NastaveniRoute
  '/navod': typeof NavodRoute
  '/prehled': typeof PrehledRoute
  '/faktury/nova': typeof FakturyNovaRoute
  '/faktury/': typeof FakturyIndexRoute
  '/faktury/$id/upravit': typeof FakturyIdUpravitRoute
  '/faktury/$id/': typeof FakturyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nastaveni'
    | '/navod'
    | '/prehled'
    | '/faktury/nova'
    | '/faktury/'
    | '/faktury/$id/upravit'
    | '/faktury/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nastaveni'
    | '/navod'
    | '/prehled'
    | '/faktury/nova'
    | '/faktury'
    | '/faktury/$id/upravit'
    | '/faktury/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/nastaveni'
    | '/navod'
    | '/prehled'
    | '/faktury/nova'
    | '/faktury/'
    | '/faktury/$id/upravit'
    | '/faktury/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NastaveniRoute: typeof NastaveniRoute
  NavodRoute: typeof NavodRoute
  PrehledRoute: typeof PrehledRoute
  FakturyNovaRoute: typeof FakturyNovaRoute
  FakturyIndexRoute: typeof FakturyIndexRoute
  FakturyIdUpravitRoute: typeof FakturyIdUpravitRoute
  FakturyIdIndexRoute: typeof FakturyIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nastaveni': {
      id: '/nastaveni'
      path: '/nastaveni'
      fullPath: '/nastaveni'
      preLoaderRoute: typeof NastaveniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navod': {
      id: '/navod'
      path: '/navod'
      fullPath: '/navod'
      preLoaderRoute: typeof NavodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prehled': {
      id: '/prehled'
      path: '/prehled'
      fullPath: '/prehled'
      preLoaderRoute: typeof PrehledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faktury/': {
      id: '/faktury/'
      path: '/faktury'
      fullPath: '/faktury/'
      preLoaderRoute: typeof FakturyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faktury/nova': {
      id: '/faktury/nova'
      path: '/faktury/nova'
      fullPath: '/faktury/nova'
      preLoaderRoute: typeof FakturyNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faktury/$id/': {
      id: '/faktury/$id/'
      path: '/faktury/$id'
      fullPath: '/faktury/$id/'
      preLoaderRoute: typeof FakturyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faktury/$id/upravit': {
      id: '/faktury/$id/upravit'
      path: '/faktury/$id/upravit'
      fullPath: '/faktury/$id/upravit'
      preLoaderRoute: typeof FakturyIdUpravitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NastaveniRoute: NastaveniRoute,
  NavodRoute: NavodRoute,
  PrehledRoute: PrehledRoute,
  FakturyNovaRoute: FakturyNovaRoute,
  FakturyIndexRoute: FakturyIndexRoute,
  FakturyIdUpravitRoute: FakturyIdUpravitRoute,
  FakturyIdIndexRoute: FakturyIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
